/*
 * Storybook Picture-Book theme — family checklists data.
 * Rendered as interactive tick-lists, synced live to both phones — fully digital,
 * nothing needs printing.
 */

export interface Checklist {
  id: string;
  title: string;
  emoji: string;
  cadence: string;
  items: string[];
}

export const CHECKLISTS: Checklist[] = [
  {
    id: "daily",
    title: "Daily",
    emoji: "☀️",
    cadence: "Every day",
    items: [
      "Fresh water (wash bowl, refill)",
      "Meals measured & fed (3×/day under ~16 weeks, then 2×)",
      "Eye wipe + dry the under-eye fur",
      "Beard blotted after drinks",
      "Toilet trips after every meal, nap and play",
      "Training micro-session (2–5 minutes)",
      "One new positive experience (socialisation window!)",
      "Play + enforced nap cycles",
      "Quick body feel-over during a cuddle (lumps, ticks, sore spots)",
      "Tick check — ears, face, neck, toes (Queensland!)",
      "Afternoon water top-up + hydration check (tropical heat — bowl never runs low)",
      "Paw-pad check after walks (hot pavement burns, cracks, grass seeds between toes)",
    ],
  },
  {
    id: "weekly",
    title: "Weekly",
    emoji: "📅",
    cadence: "Every week",
    items: [
      "Line brush 3–4 sessions + metal comb check",
      "S.C.E.N.T. check: Skin, Coat, Ears, Nails, Teeth",
      "Nail grinder ×3 micro-sessions (Mon/Wed/Sat) — 1–2 s per nail, treats between toes",
      "Ear sniff-and-look (pale pink, no smell = good)",
      "Weigh-in and log it (puppies grow fast)",
      "Wash bedding & soft toys",
      "Rotate the toy box",
      "Refill three frozen Kongs",
      "Trim eye-corner hair if wicking tears",
      "Check harness fit — puppies outgrow it in weeks",
      "Mid-week sanitary/bum check — quick look + tidy under the tail (long coat traps mess)",
      "Food-quantity review — recalibrate portions against this week's weigh-in and the weight curve",
      "Crate + pen deep-clean (wipe trays and bars, air the den — bedding wash is separate)",
      "Toy safety audit — bin torn squeakers, loose parts, shredded rope ends",
      "Training progression review — which cue graduated this week, what's next on the plan",
      "Photo/memory prompt — same spot, same blanket, straight into Memories",
      "Human jobs: restock poo-bag dispensers on BOTH leads, charge the puppy cam, check enzyme-cleaner stock",
    ],
  },
  {
    id: "monthly",
    title: "Monthly",
    emoji: "🗓️",
    cadence: "Every month",
    items: [
      "Two bath + basic-trim sessions done this month (fortnightly Mondays — see Bath Day list)",
      "Nail length audit — grinder sessions (Mon/Wed/Sat) should mean no clicking on the floor",
      "Flea / tick / worm preventatives given & logged (dose day: the 24th)",
      "Check flea/tick topical + collar expiry dates — separate from the monthly chew if using both",
      "Paw-pad + sanitary trim double-check (maintained at every bath — catch anything missed)",
      "Weight photo + coat photo (watch the red fade!) — coat photos go in the Coat length check series",
      "Restock: poo bags, treats, shampoo, styptic powder",
      "Coat-length audit — fortnightly bath-time trims should be holding him at the set teddy length; book a professional shaping groom only if the shape has drifted",
    ],
  },
  {
    id: "puppy-arrival",
    title: "Puppy Arrival",
    emoji: "🏡",
    cadence: "Before 24 Sep 2026",
    items: [
      "Crate + divider, set up in a quiet corner",
      "Playpen and/or baby gates",
      "Same food the breeder uses (2+ weeks' worth)",
      "Bowls: stainless or ceramic, one narrow water bowl",
      "Collar + ID tag + lightweight lead + Y-front harness",
      "Slicker brush + metal comb + puppy shampoo",
      "Chew toys ×6+, teething toys, lick mat, Kong",
      "Puppy pads / enzyme cleaner for accidents",
      "Vet chosen + first appointment booked",
      "Pet insurance activated from day one",
      "Tick preventative plan confirmed with vet (QLD)",
      "House rules agreed by whole family (sofa? rooms? sleep spot?)",
      "Cables hidden, toxic plants removed, bins secured",
      "Toilet spot chosen; everyone knows the routine",
      "Mum-scented blanket goes straight in the crate",
    ],
  },
  {
    id: "grooming-day",
    title: "Grooming Day (full session)",
    emoji: "✂️",
    cadence: "Every bath is a groom — fortnightly Mondays",
    items: [
      "Dog exercised first (a tired dog stands stiller)",
      "EVERYTHING laid out before he's in the room: slicker, comb, clippers oiled, 13 mm + 16–19 mm guards, scissors, ear wipes, cotton balls, towels ×3, dryer",
      "Lick mat loaded and stuck up; treat jar within reach",
      "Full line brush + comb check BEFORE any water (water sets mats)",
      "Bath: lukewarm 37–38 °C tested on your wrist; lather TWICE (rinse between)",
      "Cotton ball resting loosely at each ear opening for bath + dry",
      "Wash attention zones: armpits, groin, under tail, paw pads, beard",
      "Rinse until water runs clear — then one more full pass (armpits, belly, behind ears trap suds)",
      "Blow-dry low heat, WITH the growth direction, brush following the nozzle; ears + face last on lowest setting",
      "Maintenance trim EVERY session — hold the set length: 13 mm guard body top-up, WITH the coat growth, blade flat",
      "Legs + tail: 16–19 mm guard or comb-and-scissor — always longer than the body",
      "Face, eye corners, paw pads + sanitary tidy — the basic trim finishes every bath",
      "Blade heat checked on your wrist every few minutes",
      "If patience runs out, finish face & feet tomorrow — but never skip them for the fortnight",
      "Nails NOT today — grinder runs Mon/Wed/Sat as its own micro-sessions",
      "Coat check photo — same spot, same angle, side-on (Memories → Coat length check)",
      "Big treat party at the end — always end on a win",
    ],
  },
  {
    id: "bath-day",
    title: "Bath + Trim Day",
    emoji: "🛁",
    cadence: "Every 2 weeks — bath always ends with a basic trim",
    items: [
      "Brush + comb check FIRST (never bathe a matted coat)",
      "Cotton-wool ball loosely at ear openings — never inside the canal",
      "Lukewarm 37–38 °C water (test on your wrist), diluted dog shampoo",
      "Two lathers: first cuts dirt, second actually cleans — rinse between",
      "Fingers along the coat, no circular scrubbing; extra time on armpits, groin, under tail, paws, beard",
      "Conditioner, wait 3–5 min, rinse extremely well (then one more pass)",
      "Squeeze + blot with microfibre (no rubbing)",
      "Blow-dry cool/warm, section by section, brushing with the airflow",
      "Dry INSIDE the ears last (cotton ball, visible parts only)",
      "Comb check when fully dry — coat must glide before any trimming",
      "BASIC TRIM (every bath, keeps the coat at a set length — no big haircuts needed):",
      "• Eye corners + face tidy — round-tip scissors, tiny cuts pointing away from the eyes",
      "• Paw pads + around the feet — hair level with the pads, round the foot shape",
      "• Sanitary areas — 10 mm guard or careful scissor tidy, skin pulled taut",
      "• Light all-over top-up — 13 mm guard body, 16–19 mm legs/tail, just skimming back to the set length",
      "• Coat check photo (same spot, same angle — Memories → Coat length check) + big treat party — always end on a win",
    ],
  },
  {
    id: "vet-visit",
    title: "Vet Visit",
    emoji: "🩺",
    cadence: "Each appointment",
    items: [
      "Vaccination book / records",
      "List of questions written down beforehand",
      "Fresh stool sample if requested",
      "Note current food, dose dates of preventatives",
      "High-value treats — make the vet a party venue",
      "Practise happy 'just visiting' drop-ins between appointments",
      "Photos/videos of anything intermittent (limps, coughs, odd behaviour)",
      "Update the vaccine tracker in this app afterwards",
    ],
  },
  {
    id: "travel",
    title: "Travel / Day Out",
    emoji: "🚗",
    cadence: "Every trip",
    items: [
      "Seatbelt tether or travel crate secured",
      "Water + collapsible bowl",
      "Poo bags (more than you think)",
      "Treats + a chew for waiting time",
      "Towel + wet wipes",
      "Spare lead",
      "ID tag on, phone number current",
      "Shade plan — never leave a dog in a parked car, even minutes",
    ],
  },
  {
    id: "singapore-move",
    title: "Singapore Move",
    emoji: "✈️",
    cadence: "Sep 2026",
    items: [
      "Jet Pets booked, quote accepted — flight 23/24 Sep 2026 (he flies at 12w5d)",
      "IATA crate at home early — feed meals in it for weeks",
      "PALS dog licence obtained (needed before import licence)",
      "AVS import licence applied (~S$50, valid 30 days)",
      "Vaccination records complete & copied (Protech C3: 11 Aug / 25 Aug / 8 Sep)",
      "Accredited-vet health check + DAFF export docs (Jet Pets handles)",
      "Mum-scented blanket / worn t-shirt in the crate for the flight",
      "No sedation (vet consensus for flying)",
      "No food ~4 hours before flight; water available",
      "New-home setup ready in Singapore: crate corner, bowls, food supply",
      "Singapore vet chosen; heartworm + tick prevention plan",
      "First week in SG: quiet settling, short cool-hour walks",
    ],
  },
  {
    id: "emergency",
    title: "Emergency Kit",
    emoji: "🚑",
    cadence: "Assemble once, check quarterly",
    items: [
      "Emergency vet name, address & phone saved on both phones + pinned in this app",
      "Styptic powder",
      "Saline eye/wound wash",
      "Bandage roll + non-stick pads + vet wrap",
      "Tick remover tool (critical in QLD)",
      "Digital thermometer (dog normal ≈ 38.3–39.2 °C)",
      "3% hydrogen peroxide (ONLY if a vet instructs, to induce vomiting)",
      "Blunt-tip scissors + tweezers",
      "Spare lead + soft muzzle (hurt dogs may bite)",
      "Towel + instant cold pack",
      "Copy of vaccination records",
      "Poison hotline number saved",
    ],
  },
];
