/*
 * Storybook Picture-Book theme — printable checklists data.
 * Rendered as interactive tick-lists with localStorage state + print stylesheet.
 */

export interface Checklist {
  id: string;
  title: string;
  emoji: string;
  cadence: string;
  items: string[];
}

export const CHECKLISTS: Checklist[] = [
  {
    id: "daily",
    title: "Daily",
    emoji: "☀️",
    cadence: "Every day",
    items: [
      "Fresh water (wash bowl, refill)",
      "Meals measured & fed (3×/day under ~16 weeks, then 2×)",
      "Eye wipe + dry the under-eye fur",
      "Beard blotted after drinks",
      "Toilet trips after every meal, nap and play",
      "Training micro-session (2–5 minutes)",
      "One new positive experience (socialisation window!)",
      "Play + enforced nap cycles",
      "Quick body feel-over during a cuddle (lumps, ticks, sore spots)",
      "Tick check — ears, face, neck, toes (Queensland!)",
    ],
  },
  {
    id: "weekly",
    title: "Weekly",
    emoji: "📅",
    cadence: "Every week",
    items: [
      "Line brush 3–4 sessions + metal comb check",
      "S.C.E.N.T. check: Skin, Coat, Ears, Nails, Teeth",
      "Ear sniff-and-look (pale pink, no smell = good)",
      "Weigh-in and log it (puppies grow fast)",
      "Wash bedding & soft toys",
      "Rotate the toy box",
      "Refill three frozen Kongs",
      "Trim eye-corner hair if wicking tears",
      "Check harness fit — puppies outgrow it in weeks",
    ],
  },
  {
    id: "monthly",
    title: "Monthly",
    emoji: "🗓️",
    cadence: "Every month",
    items: [
      "Bath + conditioner + full fluff dry",
      "Nail trim or grind (every 3–4 weeks)",
      "Flea / tick / worm preventatives given & logged",
      "Paw-pad hair trim",
      "Sanitary tidy",
      "Weight photo + coat photo (watch the red fade!)",
      "Restock: poo bags, treats, shampoo, styptic powder",
      "Book next groom (every 4–6 weeks once adult coat is in)",
    ],
  },
  {
    id: "puppy-arrival",
    title: "Puppy Arrival",
    emoji: "🏡",
    cadence: "Before 21 Aug 2026",
    items: [
      "Crate + divider, set up in a quiet corner",
      "Playpen and/or baby gates",
      "Same food the breeder uses (2+ weeks' worth)",
      "Bowls: stainless or ceramic, one narrow water bowl",
      "Collar + ID tag + lightweight lead + Y-front harness",
      "Slicker brush + metal comb + puppy shampoo",
      "Chew toys ×6+, teething toys, lick mat, Kong",
      "Puppy pads / enzyme cleaner for accidents",
      "Vet chosen + first appointment booked",
      "Pet insurance activated from day one",
      "Tick preventative plan confirmed with vet (QLD)",
      "House rules agreed by whole family (sofa? rooms? sleep spot?)",
      "Cables hidden, toxic plants removed, bins secured",
      "Toilet spot chosen; everyone knows the routine",
      "Mum-scented blanket goes straight in the crate",
    ],
  },
  {
    id: "grooming-day",
    title: "Grooming Day",
    emoji: "✂️",
    cadence: "Home groom sessions",
    items: [
      "Dog exercised first (a tired dog stands stiller)",
      "Full line brush + comb check BEFORE any water",
      "Tools laid out: slicker, comb, clippers oiled, guards, scissors",
      "Lick mat loaded and stuck up",
      "Towels + dryer ready",
      "Nails first while patience is full",
      "Body clip WITH the coat growth, blade flat",
      "Blade heat checked on wrist every few minutes",
      "Face & feet another day if patience runs out (that's fine)",
      "Finish photo for the style folder",
      "Big treat party at the end — always end on a win",
    ],
  },
  {
    id: "bath-day",
    title: "Bath Day",
    emoji: "🛁",
    cadence: "Every 3–4 weeks",
    items: [
      "Brush + comb check FIRST (never bathe a matted coat)",
      "Cotton-wool ball loosely at ear openings (optional) — never inside the canal",
      "Lukewarm water, diluted dog shampoo",
      "Fingers along the coat, no circular scrubbing",
      "Conditioner, wait 3–5 min, rinse extremely well",
      "Squeeze + blot with microfibre (no rubbing)",
      "Blow-dry cool/warm, section by section, brushing with the airflow",
      "Dry INSIDE the ears last (cotton ball, visible parts only)",
      "Comb check when fully dry",
    ],
  },
  {
    id: "vet-visit",
    title: "Vet Visit",
    emoji: "🩺",
    cadence: "Each appointment",
    items: [
      "Vaccination book / records",
      "List of questions written down beforehand",
      "Fresh stool sample if requested",
      "Note current food, dose dates of preventatives",
      "High-value treats — make the vet a party venue",
      "Practise happy 'just visiting' drop-ins between appointments",
      "Photos/videos of anything intermittent (limps, coughs, odd behaviour)",
      "Update the vaccine tracker in this app afterwards",
    ],
  },
  {
    id: "travel",
    title: "Travel / Day Out",
    emoji: "🚗",
    cadence: "Every trip",
    items: [
      "Seatbelt tether or travel crate secured",
      "Water + collapsible bowl",
      "Poo bags (more than you think)",
      "Treats + a chew for waiting time",
      "Towel + wet wipes",
      "Spare lead",
      "ID tag on, phone number current",
      "Shade plan — never leave a dog in a parked car, even minutes",
    ],
  },
  {
    id: "singapore-move",
    title: "Singapore Move",
    emoji: "✈️",
    cadence: "Sep 2026",
    items: [
      "Jetpets booked, quote accepted, flight date set (12+ weeks: from 18 Sep)",
      "IATA crate at home early — feed meals in it for weeks",
      "PALS dog licence obtained (needed before import licence)",
      "AVS import licence applied (~S$50, valid 30 days)",
      "Vaccination records complete & copied",
      "Accredited-vet health check + DAFF export docs (Jetpets handles)",
      "Mum-scented blanket / worn t-shirt in the crate for the flight",
      "No sedation (vet consensus for flying)",
      "No food ~4 hours before flight; water available",
      "New-home setup ready in Singapore: crate corner, bowls, food supply",
      "Singapore vet chosen; heartworm + tick prevention plan",
      "First week in SG: quiet settling, short cool-hour walks",
    ],
  },
  {
    id: "emergency",
    title: "Emergency Kit",
    emoji: "🚑",
    cadence: "Assemble once, check quarterly",
    items: [
      "Emergency vet name, address & phone saved + printed",
      "Styptic powder",
      "Saline eye/wound wash",
      "Bandage roll + non-stick pads + vet wrap",
      "Tick remover tool (critical in QLD)",
      "Digital thermometer (dog normal ≈ 38.3–39.2 °C)",
      "3% hydrogen peroxide (ONLY if a vet instructs, to induce vomiting)",
      "Blunt-tip scissors + tweezers",
      "Spare lead + soft muzzle (hurt dogs may bite)",
      "Towel + instant cold pack",
      "Copy of vaccination records",
      "Poison hotline number saved",
    ],
  },
];
