/*
 * Storybook Picture-Book theme — "100 Things Owners Learn Too Late".
 * Short, practical, fact-checked items. Categorised for browsing.
 */

export interface HundredCategory {
  id: string;
  title: string;
  emoji: string;
  items: string[];
}

export const HUNDRED: HundredCategory[] = [
  {
    id: "coat",
    title: "The Coat",
    emoji: "🧶",
    items: [
      "'Non-shedding' means the hair stays IN the coat and mats — it's a grooming commitment, not a discount.",
      "The coat change at 6–12 months is the single biggest grooming crisis of a doodle's life. Nobody warns you.",
      "Mats are judged with a metal comb at the skin, not a slicker on the surface.",
      "Water tightens mats. A bath before brushing turns tangles into felt.",
      "Never let the coat air-dry — a fleece coat dries into tangles. Blow-dry and brush.",
      "Behind the ears mats first, every single time. Check it daily.",
      "Where the harness sits will mat. Take the harness off at home.",
      "Red coats usually fade — rich red often mellows to apricot by age two. Take monthly photos.",
      "A shaved-down doodle regrows its full coat in 2–3 months. It's hair, not a tragedy.",
      "Conditioner every bath isn't a luxury on a fleece coat — it's mat prevention.",
      "A freshly clipped fleece coat looks straight for a few days, then the wave bounces back. Don't panic.",
      "Humidity is the enemy: in the tropics, matting speed roughly doubles. Cut shorter, brush more.",
    ],
  },
  {
    id: "grooming",
    title: "Grooming",
    emoji: "✂️",
    items: [
      "Start handling paws, ears and muzzle from day one home — the grooming battle is won months before the first haircut.",
      "The first groom (~16 weeks) should be short and happy, not a full makeover. It sets the tone for life.",
      "Bring photos to the groomer. 'Teddy bear cut' means something different in every salon.",
      "Say 'don't poodle my doodle' if you want a round face, not a shaved poodle muzzle.",
      "Brushing only the fluffy top layer is how dogs end up shaved. Line brush to the skin.",
      "Mist before you brush — brushing a bone-dry coat breaks hair and causes static.",
      "Never point scissors at a mat. Clip under it or split it with thinning shears.",
      "A groomer's 'bath and tidy' between full grooms costs half as much and keeps the coat workable.",
      "Cheap clippers that jam and pull hurt — and one bad clipper experience can take months to undo.",
      "Blades get HOT. Check against your wrist every few minutes.",
      "Trim the hair between paw pads — overgrown pad hair makes dogs slip on tiles.",
      "Never shave between the eyes. It takes months to grow back.",
      "Dogs hear the dryer at a volume you can't imagine. Desensitise in 1-minute sessions, and buy a Happy Hoodie.",
      "Grooming little and often beats marathon sessions: body one day, face another.",
      "Teach a chin rest. A dog who consents to grooming is calmer than a dog who's restrained for it.",
      "Human shampoo — even baby shampoo — is the wrong pH for dog skin. Dog products only.",
    ],
  },
  {
    id: "puppyhood",
    title: "Puppyhood",
    emoji: "🐶",
    items: [
      "An overtired puppy looks like a badly behaved puppy. Nearly all 'crazy biting' is exhaustion — enforce naps.",
      "Puppies need 18–20 hours of sleep a day. Yes, really.",
      "The socialisation window closes around 16 weeks. It is the highest-leverage project of the dog's life.",
      "Socialisation means positive exposure at the puppy's pace — not being mobbed at a dog park.",
      "Carry the puppy everywhere before vaccinations finish. Being carried counts as socialisation with zero disease risk.",
      "Fear periods are real — and landing at 12 weeks after a long flight is a lot. Keep homecoming week gentle and boring.",
      "A second fear period hits around 6–14 months. A confident adolescent suddenly spooking is normal; stay calm.",
      "Comfort a crying puppy at night. Ignoring them doesn't build character, it builds anxiety.",
      "Puppy teeth are needles and teething peaks around 4–6 months. Frozen washcloths and frozen Kongs save furniture.",
      "The 'puppy licence' with adult dogs expires around 4–5 months — rude adolescent puppies get corrected.",
      "Toilet training regressions at 4–6 months are normal, not failure.",
      "Bell training works: hang a bell on the door, tap it before every toilet trip, and one day they'll ring it themselves.",
      "Never punish a toileting accident — it just teaches the puppy to hide and go behind the sofa.",
      "Keep a 'party voice' recall word that ALWAYS means treats and never means bath, nails or leaving the park.",
      "Feed meals in the crate from day one. A crate that means dinner is a crate he loves.",
    ],
  },
  {
    id: "cavoodle",
    title: "Cavoodle Quirks",
    emoji: "🦴",
    items: [
      "Cavoodles are velcro dogs. Separation anxiety is their #1 behaviour issue — train alone-time from week one.",
      "Practise leaving for 30 seconds, then 2 minutes, then 10. Boring departures, boring returns.",
      "Those Cavalier eyes are professional-grade food-begging equipment. The whole family must agree: no table scraps, ever.",
      "Cavoodles are smart enough to learn anything — including things you didn't mean to teach (like 'barking opens doors').",
      "They're prone to weight gain, and extra weight is brutal on small joints. You should feel ribs easily.",
      "Long ears + hairy ear canals = ear infection factory. A weekly sniff-check takes ten seconds.",
      "Tear stains show brutally on a white face. A 60-second daily eye wipe beats every miracle product.",
      "Small dogs' teeth crowd and rot early. Daily brushing from puppyhood — dental disease is the most common (and most preventable) health issue.",
      "Cavoodles often keep puppy energy to age two, then mellow beautifully.",
      "That head tilt when you speak? Weaponise it for photos. You'll want thousands.",
      "A bored Cavoodle barks. A sniffed-out, trained, enriched Cavoodle naps. Choose your afternoon.",
    ],
  },
  {
    id: "money",
    title: "Money & Gear",
    emoji: "💰",
    items: [
      "The purchase price is the cheap part. Budget for insurance, grooming every 4–6 weeks, food, vet care and gear.",
      "Pet insurance is cheapest and easiest BEFORE anything is 'pre-existing'. Insure from day one.",
      "Professional grooming for life costs thousands. A A$300 home setup pays for itself within a year.",
      "Buy the good slicker brush and metal comb first. They're your daily drivers; everything else can be budget.",
      "Concentrated pro shampoo dilutes 10:1 or more — a big bottle lasts a year and beats supermarket bottles.",
      "You need double the chew toys you think, on rotation. A 'new' toy from the cupboard beats a new toy from the shop.",
      "Skip the fancy bed at first — puppies chew beds. Vetbed offcuts and old towels until adulthood.",
      "The crate is the single best investment. Buy adult size with a divider.",
      "A cheap washable rug beats an expensive carpet for the entire first year.",
      "Groomers charge extra for matted coats — brushing at home is literally money in the bank.",
      "Styptic powder costs $10 and turns a bleeding nail-quick disaster into a non-event. Buy it before you need it.",
    ],
  },
  {
    id: "daily",
    title: "Daily Life",
    emoji: "🏠",
    items: [
      "Set up a dog station by the door: leads, towel, treats, poo bags. Chaos becomes a 10-second exit.",
      "Freeze three stuffed Kongs every Sunday — emergency enrichment on tap all week.",
      "A snuffle mat or scatter-fed dinner tires a dog out more than you'd expect. Sniffing is exhausting.",
      "Ten minutes of training tires a puppy more than an hour of zoomies.",
      "Wet-weather plan: lick mats, puzzle feeders and hide-and-seek indoors. A bored Cavoodle invents its own games; you won't like them.",
      "Blot the beard after every drink or the chin stays damp — damp chins go pink and smelly.",
      "Elevate the water bowl slightly and use a narrow one to keep the ears out.",
      "A snood at dinner keeps long ears out of the bowl. Ridiculous-looking, life-changing.",
      "Keep an 'emergency kit' in the car: towel, water, bowl, spare lead, poo bags, treats.",
      "The 7-second rule: if pavement is too hot for the back of your hand for 7 seconds, it's too hot for paws.",
      "Take a photo on grooming day, every time. The folder becomes your groomer-communication superpower.",
      "Trade, never chase. Chasing a puppy carrying your sock turns sock-theft into the best game ever invented.",
      "Name every item as you give it: 'ball', 'bone', 'bunny'. In a year you'll have a dog who fetches by name.",
    ],
  },
  {
    id: "health",
    title: "Health & Safety",
    emoji: "🏥",
    items: [
      "Know the poison list cold: chocolate, grapes/raisins, onions, garlic, xylitol (in sugar-free gum and some peanut butters), macadamias, lilies.",
      "Check the peanut butter label EVERY time. Xylitol can be fatal in tiny doses.",
      "In Queensland, paralysis ticks kill dogs. Preventatives plus daily fingertip checks after grass time — non-negotiable until the move.",
      "Learn your emergency vet's address and number now, not during the emergency.",
      "A normal resting puppy breathes about 15–35 breaths a minute. Knowing his baseline makes 'something's wrong' obvious.",
      "Poo is data. A sudden change lasting more than a day, blood, or black tar = vet call.",
      "Puppies can't hold overnight at first — a 3 am toilet trip for a few weeks is the price of admission.",
      "Vaccination isn't finished until ~2 weeks after the FINAL puppy dose. Mark the true 'free to roam' date.",
      "Desexing timing for small breeds is a genuine vet conversation, not a default date.",
      "Dogs hide pain. Reluctance to jump, sudden grumpiness or licking one spot are pain until proven otherwise.",
      "Keep a 'gotcha kit' by the door for escapes: squeaky toy + treats. Chasing a loose dog makes it a game; running AWAY brings them back.",
    ],
  },
  {
    id: "mindset",
    title: "Mindset",
    emoji: "💛",
    items: [
      "The first two weeks are hard. 'Puppy blues' are real and they pass.",
      "You will make mistakes. Dogs are gloriously forgiving; consistency beats perfection.",
      "Comparison is the thief of joy — the internet's puppies are highlight reels.",
      "Train the dog in front of you, not the breed description.",
      "Every interaction is training, whether you meant it or not.",
      "A tired dog isn't automatically a happy dog — enrichment beats exhaustion.",
      "Your calm is contagious. So is your panic.",
      "The destruction phase ends. The velcro shadow at your feet lasts fifteen years.",
      "Take more photos and videos than feels reasonable. Puppyhood lasts about twenty minutes.",
      "One day the crazy landshark puppy quietly puts his head on your knee, and every 3 am toilet trip becomes worth it.",
      "Fifteen years from now you won't remember the chewed shoe. Write the funny disasters down — this handbook has trackers for a reason.",
    ],
  },
];

export const HUNDRED_TOTAL = HUNDRED.reduce((n, c) => n + c.items.length, 0);
