/*
 * Daily socialisation missions for Paddington Today.
 * Deterministic by calendar date. First-timer instruction cards for Marcus
 * and Chesa, who have never owned a dog. Pre-clearance = carry only.
 */
import {
  CORE_16W_ISO,
  HOMECOMING_ISO,
  dayIndex,
  groundWalksAllowed,
  hasLanded,
} from "./household";

export type SocialCategory = "carry" | "people" | "noise" | "car" | "handling" | "ground";

export interface SocialMission {
  id: string;
  category: SocialCategory;
  title: string;
  emoji: string;
  minutes: number;
  why: string;
  bring: string[];
  steps: string[];
  goodLooksLike: string;
  ifScared: string;
  whenToStop: string;
  safety: string[];
  handbookHref: string;
  logCategory: string;
  logPrompt: string;
}

/** Paws off public ground until the 16 Oct core plus a SingVet nod. */
export const PRECLEAR_SAFETY: string[] = [
  "Paws off public ground. Parvo and other diseases live in soil and grass and can survive for months. His third shot on 4 Sep is not full protection.",
  "No greeting strange dogs. You do not know their vaccination status. One sniff from a sick dog is enough.",
  "No sniffing pee spots or other dogs' droppings. Disease spreads this way, even if his paws never touch the grass.",
  "Let him choose whether to approach people. A grabbed-at puppy learns that strangers are scary.",
  "Never pass him around a circle of hands. One calm person at a time, and only if he leans in.",
  "Pair every new thing with treats. A pea-sized treat from your hand to his mouth within two seconds of the thing happening.",
  "End the session while he is still comfortable. Stop the moment he stops taking treats.",
];

const TREAT_POUCH = "Treat pouch with pea-sized treats (his usual kibble or tiny chicken bits)";
const CARRIER = "His carrier, zipped, with the travel blanket inside";
const WATER = "A small bottle of water for you. He should not drink from public bowls.";
const POOP_BAG = "A poop bag, even though he will not toilet outside. Habit for later.";

const BRING_CARRY = [TREAT_POUCH, CARRIER, WATER, POOP_BAG];
const BRING_INDOOR = [TREAT_POUCH, "A towel on your lap so he has grip"];
const BRING_CAR = [TREAT_POUCH, CARRIER, "His harness stays on inside the carrier. He is never loose in the car."];

function scaredCopy(): string {
  return "Increase distance. Let him watch from further away. Treats rain from the sky (pea-sized bits, one after another). Leave calmly. Never drag him closer. Never panic-comfort (high baby-talk and clutching tell him this is an emergency).";
}

function stopCopy(minutes: number): string {
  return `The moment he stops taking treats, or he is still happy when ${minutes} minutes are up, whichever comes first.`;
}

const INDOOR_MISSIONS: SocialMission[] = [
  {
    id: "indoor-paws",
    category: "handling",
    title: "Paw holds on the sofa",
    emoji: "🤲",
    minutes: 5,
    why: "Socialization means teaching him the world is safe, one small experience at a time. Today the world is just your hands on his paws, so Monday nail trims later are not a wrestle.",
    bring: BRING_INDOOR,
    steps: [
      "Sit on the sofa with him on a towel on your lap, facing away from the TV.",
      "Let him settle and take two pea-sized treats for just sitting there.",
      "Touch one front paw for one second. Put a pea-sized treat in his mouth within two seconds.",
      "Repeat on the other front paw. Then each back paw. Stop if he pulls away.",
      "If he stays loose, hold one paw three seconds and treat. That is the whole session.",
    ],
    goodLooksLike: "Loose body, taking treats, maybe licking your hand. A little fidget is fine. Frozen or tucked tail is not.",
    ifScared: scaredCopy(),
    whenToStop: stopCopy(5),
    safety: PRECLEAR_SAFETY,
    handbookHref: "/training?open=handling",
    logCategory: "Handling / body touch",
    logPrompt: "Log this in Socialisation as Handling / body touch.",
  },
  {
    id: "indoor-thunder",
    category: "noise",
    title: "Thunder from the window",
    emoji: "⛈️",
    minutes: 8,
    why: "Singapore storms are loud and they will happen for the next 15 years of his life. Counter-conditioning means the scary thing starts predicting treats, so thunder becomes 'chicken is coming' instead of 'the sky is ending'.",
    bring: BRING_INDOOR,
    steps: [
      "When rain or thunder starts, sit with him on your lap at a window, a few metres back. Do not press him to the glass.",
      "The first rumble: a pea-sized treat in his mouth within two seconds.",
      "Keep a slow stream of treats as long as the noise continues and he is still eating.",
      "If he looks at the window, quietly say 'yes' and treat. Looking is allowed. Panicking is the stop line.",
      "When the burst fades, one last treat and put him down for a nap. Do not make a fuss.",
    ],
    goodLooksLike: "Curious glances at the window, still taking treats, body not glued to you.",
    ifScared: scaredCopy(),
    whenToStop: stopCopy(8),
    safety: PRECLEAR_SAFETY,
    handbookHref: "/training?open=social",
    logCategory: "New sound",
    logPrompt: "Log this in Socialisation as New sound.",
  },
  {
    id: "indoor-carrier",
    category: "car",
    title: "Carrier on the living-room floor",
    emoji: "🧳",
    minutes: 6,
    why: "Car rides later only work if the carrier already means snacks. Today he learns the box is a den, not a trap, without leaving the flat.",
    bring: [TREAT_POUCH, CARRIER],
    steps: [
      "Put the carrier on the living-room floor with the door open and the blanket inside.",
      "Toss three pea-sized treats just inside the door. Let him walk in on his own. Do not push.",
      "When both front paws are in, a treat in his mouth within two seconds.",
      "Sit next to the carrier and feed two more treats through the door. Close the door for five seconds, treat through the grid, then open it.",
      "Repeat once. Then leave the carrier open as a snack cave for the rest of the afternoon.",
    ],
    goodLooksLike: "Walking in without being shoved, taking treats inside, coming back out when he wants.",
    ifScared: scaredCopy(),
    whenToStop: stopCopy(6),
    safety: PRECLEAR_SAFETY,
    handbookHref: "/training?open=social",
    logCategory: "Car / transport",
    logPrompt: "Log this in Socialisation as Car / transport.",
  },
  {
    id: "indoor-ears",
    category: "handling",
    title: "Ear flaps and a treat rain",
    emoji: "👂",
    minutes: 5,
    why: "Cavoodle drop ears trap Singapore humidity. A one-second ear lift now, paid in treats, is how Monday ear checks stay easy.",
    bring: BRING_INDOOR,
    steps: [
      "Sit with him on your lap. Treat for sitting.",
      "Lift one ear flap for one second. Pea-sized treat in his mouth within two seconds.",
      "Same on the other ear.",
      "If he stays loose, glance inside the ear (do not poke) and treat.",
      "Stop. Put him down. That is enough for day one of ears.",
    ],
    goodLooksLike: "Loose body, taking treats, maybe a head shake after. No freeze.",
    ifScared: scaredCopy(),
    whenToStop: stopCopy(5),
    safety: PRECLEAR_SAFETY,
    handbookHref: "/training?open=handling",
    logCategory: "Handling / body touch",
    logPrompt: "Log this in Socialisation as Handling / body touch.",
  },
];

const CARRY_MISSIONS: SocialMission[] = [
  {
    id: "carry-block",
    category: "carry",
    title: "A different block, in your arms",
    emoji: "🚶",
    minutes: 8,
    why: "Socialization means teaching him the world is safe, one small experience at a time. A new block is new smells, new corridor paint, new lift buttons, with his paws off the ground.",
    bring: BRING_CARRY,
    steps: [
      "Put him in the carrier or hold him in your arms. Zip or hold so he cannot wriggle onto the floor.",
      "Walk to a neighbouring block, not yours. Take the lift if there is one.",
      "Stand in that lobby for three minutes. Let him look. A pea-sized treat in his mouth within two seconds of any new sound or person.",
      "Walk the length of one corridor and back. Treat for looking, not for struggling.",
      "Go home the same way. Last treat at your own door.",
    ],
    goodLooksLike: "Loose body, taking treats, curious glances at the new lobby.",
    ifScared: scaredCopy(),
    whenToStop: stopCopy(8),
    safety: PRECLEAR_SAFETY,
    handbookHref: "/training?open=social",
    logCategory: "New place",
    logPrompt: "Log this in Socialisation as New place.",
  },
  {
    id: "carry-lift",
    category: "carry",
    title: "Lift with strangers",
    emoji: "🛗",
    minutes: 6,
    why: "HDB life is lifts. He needs the ding, the close of doors, and other people in a small box to feel normal, from your arms.",
    bring: BRING_CARRY,
    steps: [
      "Hold him in your arms facing out, or in the carrier with the mesh toward the door.",
      "Call the lift. Treat when the ding happens.",
      "Ride two floors with whoever gets in. Do not let people grab his face. Smile and say 'he's in training, please don't touch'.",
      "If someone talks softly from a step away, treat him for looking at them.",
      "Ride back down. Treat at your floor. Go home.",
    ],
    goodLooksLike: "Watching the door, taking treats, not scrambling to jump down.",
    ifScared: scaredCopy(),
    whenToStop: stopCopy(6),
    safety: PRECLEAR_SAFETY,
    handbookHref: "/training?open=social",
    logCategory: "New place",
    logPrompt: "Log this in Socialisation as New place.",
  },
  {
    id: "carry-market",
    category: "carry",
    title: "Wet market's edge",
    emoji: "🥬",
    minutes: 8,
    why: "The market is smell, noise, and aunties with trolleys. From the edge, not inside the wet floor, he gets the download without the disease risk.",
    bring: BRING_CARRY,
    steps: [
      "Carry him to the entrance of the nearest wet market or provision shop strip. Stay on the dry tiled edge, not the wet floor.",
      "Stand for three minutes. Treat within two seconds of a loud call, a trolley rattle, or a new smell making his nose work.",
      "Take five steps along the edge and stop. Treat.",
      "If he looks at an auntie, treat. If she reaches, step back and say he is not for holding today.",
      "Walk home. Last treat at the door.",
    ],
    goodLooksLike: "Nose working, taking treats, glances toward the stalls. Not hiding in your armpit the whole time.",
    ifScared: scaredCopy(),
    whenToStop: stopCopy(8),
    safety: PRECLEAR_SAFETY,
    handbookHref: "/training?open=social",
    logCategory: "New place",
    logPrompt: "Log this in Socialisation as New place.",
  },
  {
    id: "carry-bus",
    category: "carry",
    title: "Bus stop watch",
    emoji: "🚌",
    minutes: 7,
    why: "Buses hiss, kneel, and smell of brakes. Watching from your arms makes that ordinary before he is ever on a bus.",
    bring: BRING_CARRY,
    steps: [
      "Carry him to a bus stop. Stand at the back of the queue area, not at the kerb.",
      "When a bus arrives, a pea-sized treat in his mouth within two seconds of the hiss.",
      "Let him watch people get on and off for two more buses, or five minutes, whichever is shorter.",
      "If someone wants to pet, smile, step a half-step back, and treat him for looking.",
      "Walk home. Treat at the door.",
    ],
    goodLooksLike: "Watching the bus, taking treats, maybe a startle then a look back at you for the next treat.",
    ifScared: scaredCopy(),
    whenToStop: stopCopy(7),
    safety: PRECLEAR_SAFETY,
    handbookHref: "/training?open=social",
    logCategory: "New place",
    logPrompt: "Log this in Socialisation as New place.",
  },
  {
    id: "carry-mrt",
    category: "carry",
    title: "MRT station entrance",
    emoji: "🚇",
    minutes: 8,
    why: "The MRT rumble is Woodlands' heartbeat. He needs that vibration in his bones as 'treats are coming', not as a scare.",
    bring: BRING_CARRY,
    steps: [
      "Carry him to the station entrance. Stay outside the fare gates, on the concourse.",
      "When a train rumbles below or a gate beeps, treat within two seconds.",
      "Walk ten steps along the concourse and sit on a bench with him on your lap for three minutes.",
      "Treat for looking at commuters. Do not let a circle of hands form.",
      "Leave before the crowd peaks. Treat at home.",
    ],
    goodLooksLike: "Curious glances toward the gates, taking treats, body not glued into your chest.",
    ifScared: scaredCopy(),
    whenToStop: stopCopy(8),
    safety: PRECLEAR_SAFETY,
    handbookHref: "/training?open=social",
    logCategory: "New sound",
    logPrompt: "Log this in Socialisation as New sound.",
  },
  {
    id: "carry-void-am",
    category: "carry",
    title: "Void deck, morning quiet",
    emoji: "🌅",
    minutes: 8,
    why: "The void deck is his future neighbourhood living room. Morning is cooler and calmer, a good first sit.",
    bring: BRING_CARRY,
    steps: [
      "Sit on the void-deck bench with him on your lap. Let him watch for three minutes.",
      "Treat within two seconds of a motorbike, a closing metal gate, or someone walking past.",
      "If an uncle sits at the other end of the bench, treat Paddington for looking. Do not pass him over.",
      "Stand, walk the length of the void deck in your arms, sit again for one minute.",
      "Go home before it gets hot. Treat at the door.",
    ],
    goodLooksLike: "Watching the car park, taking treats, maybe a wag.",
    ifScared: scaredCopy(),
    whenToStop: stopCopy(8),
    safety: PRECLEAR_SAFETY,
    handbookHref: "/training?open=social",
    logCategory: "New place",
    logPrompt: "Log this in Socialisation as New place.",
  },
  {
    id: "carry-void-pm",
    category: "carry",
    title: "Void deck, after sunset",
    emoji: "🌆",
    minutes: 8,
    why: "Evening void decks are different: fluorescent lights, dinner smells, kids on scooters. Same place, new picture.",
    bring: BRING_CARRY,
    steps: [
      "Sit on the void-deck bench with him on your lap after 7pm. Watch for three minutes.",
      "Treat for each new sound: a scooter, a football, a metal chair.",
      "If kids come close, stand up, take two steps back, treat him for looking from further away.",
      "One slow walk the length of the deck in your arms. Home.",
    ],
    goodLooksLike: "Watching the lights, taking treats, not hiding the whole time.",
    ifScared: scaredCopy(),
    whenToStop: stopCopy(8),
    safety: PRECLEAR_SAFETY,
    handbookHref: "/training?open=social",
    logCategory: "New place",
    logPrompt: "Log this in Socialisation as New place.",
  },
  {
    id: "people-uncles",
    category: "people",
    title: "Uncles with umbrellas",
    emoji: "☂️",
    minutes: 8,
    why: "Umbrellas pop open near faces. He needs that whoosh to mean a treat, not a threat.",
    bring: BRING_CARRY,
    steps: [
      "Stand under a void-deck or sheltered walkway where uncles wait with umbrellas.",
      "When one opens, treat within two seconds.",
      "If an uncle smiles, you smile back and keep Paddington on your lap. He chooses whether to look.",
      "If the uncle reaches, step back. Treat Paddington for watching from further away.",
      "Three umbrella events or eight minutes. Then home.",
    ],
    goodLooksLike: "A glance at the umbrella, then a look at you for the treat.",
    ifScared: scaredCopy(),
    whenToStop: stopCopy(8),
    safety: PRECLEAR_SAFETY,
    handbookHref: "/training?open=social",
    logCategory: "New person",
    logPrompt: "Log this in Socialisation as New person.",
  },
  {
    id: "people-aunties",
    category: "people",
    title: "Aunties with trolleys",
    emoji: "🛒",
    minutes: 7,
    why: "Trolleys rattle and they come straight at you in a corridor. He needs the rattle to predict a pea-sized treat.",
    bring: BRING_CARRY,
    steps: [
      "Stand at the side of a corridor or market edge with him in your arms.",
      "When a trolley rattles past, treat within two seconds.",
      "If an auntie stops to coo, you thank her, keep him on your chest, and treat him for looking.",
      "Do not hand him over. If she insists, 'he's in training, paws stay with us.'",
      "Home after three trolleys or seven minutes.",
    ],
    goodLooksLike: "Watching the trolley, taking treats, body loose.",
    ifScared: scaredCopy(),
    whenToStop: stopCopy(7),
    safety: PRECLEAR_SAFETY,
    handbookHref: "/training?open=social",
    logCategory: "New person",
    logPrompt: "Log this in Socialisation as New person.",
  },
  {
    id: "people-kids",
    category: "people",
    title: "Kids on scooters, at a distance",
    emoji: "🛴",
    minutes: 7,
    why: "Fast small humans are unpredictable. Distance is the whole point. Threshold is the invisible line where curious turns to worried. Stay on the curious side of that line.",
    bring: BRING_CARRY,
    steps: [
      "Find a void deck or park edge where kids scooter. Sit far enough that they are a picture, not a rush.",
      "Treat within two seconds of each zoom-past.",
      "If they come toward you, stand and take five steps back. Treat him at the new distance.",
      "Do not let them touch him. A kind 'he's learning, please give us space' is enough.",
      "Seven minutes or the moment he stops eating. Home.",
    ],
    goodLooksLike: "Watching the scooters, still taking treats. If he looks away and shuts down, you were too close.",
    ifScared: scaredCopy(),
    whenToStop: stopCopy(7),
    safety: PRECLEAR_SAFETY,
    handbookHref: "/training?open=social",
    logCategory: "New person",
    logPrompt: "Log this in Socialisation as New person.",
  },
  {
    id: "people-beards",
    category: "people",
    title: "Men with beards",
    emoji: "🧔",
    minutes: 6,
    why: "Beards, hats, and deep voices are a common puppy fright. One calm look, paid in treats, is the whole lesson.",
    bring: BRING_CARRY,
    steps: [
      "Sit on a void-deck bench with him on your lap, facing the walkway.",
      "When a bearded man walks past, treat within two seconds of Paddington noticing.",
      "If the man stops, you chat from a sit. Paddington stays on your lap. He may sniff the air. He does not have to be held by the man.",
      "Thank the man and let him walk on. One more passer-by if Paddington is still eating.",
      "Home.",
    ],
    goodLooksLike: "A look, a treat, a blink. Not a scramble into your shirt.",
    ifScared: scaredCopy(),
    whenToStop: stopCopy(6),
    safety: PRECLEAR_SAFETY,
    handbookHref: "/training?open=social",
    logCategory: "New person",
    logPrompt: "Log this in Socialisation as New person.",
  },
  {
    id: "people-uniform",
    category: "people",
    title: "Uniformed workers",
    emoji: "👷",
    minutes: 6,
    why: "Delivery vests, cleaners, and guards look like a different species to a puppy. He needs them to mean snacks.",
    bring: BRING_CARRY,
    steps: [
      "Stand near the drop-off driveway or letterbox area at a quiet time.",
      "When a uniformed worker appears, treat within two seconds of the look.",
      "Keep your distance. Do not walk up to them for a meet-and-greet.",
      "If they wave, you wave. He stays in your arms.",
      "Two uniforms or six minutes. Home.",
    ],
    goodLooksLike: "Curious glance, treat, back to watching.",
    ifScared: scaredCopy(),
    whenToStop: stopCopy(6),
    safety: PRECLEAR_SAFETY,
    handbookHref: "/training?open=social",
    logCategory: "New person",
    logPrompt: "Log this in Socialisation as New person.",
  },
  {
    id: "people-toddlers",
    category: "people",
    title: "Toddlers, visual only",
    emoji: "👶",
    minutes: 6,
    why: "Toddlers grab. He is allowed to see them. He is not a toy for them. Visual only means looking, not touching.",
    bring: BRING_CARRY,
    steps: [
      "Sit far from a playground or void-deck play corner. Toddlers should look small.",
      "Treat for each look he gives them.",
      "If a parent walks over, stand, thank them, and say he is watching today, not meeting.",
      "Do not let a toddler's hand reach his face.",
      "Six minutes. Home.",
    ],
    goodLooksLike: "Glances, treats, maybe a head tilt. No freeze.",
    ifScared: scaredCopy(),
    whenToStop: stopCopy(6),
    safety: PRECLEAR_SAFETY,
    handbookHref: "/training?open=social",
    logCategory: "New person",
    logPrompt: "Log this in Socialisation as New person.",
  },
  {
    id: "noise-hawker",
    category: "noise",
    title: "Hawker-centre clatter, from a distance",
    emoji: "🍜",
    minutes: 8,
    why: "Plates, woks, and uncle shouts are Singapore's dinner soundtrack. From across the street, not from a table yet.",
    bring: BRING_CARRY,
    steps: [
      "Stand across the road or at the far edge of a hawker centre. You should hear it, not be in it.",
      "Treat within two seconds of a bang, a shout, or a blender.",
      "Sit on a bench if there is one, him on your lap, for four minutes.",
      "If he stops eating, you are too close. Cross further away and try one more minute.",
      "Home before you get hungry enough to go in.",
    ],
    goodLooksLike: "Ear flicks, treats, watching the stalls.",
    ifScared: scaredCopy(),
    whenToStop: stopCopy(8),
    safety: PRECLEAR_SAFETY,
    handbookHref: "/training?open=social",
    logCategory: "New sound",
    logPrompt: "Log this in Socialisation as New sound.",
  },
  {
    id: "noise-school",
    category: "noise",
    title: "School-run crowd, from the side",
    emoji: "🎒",
    minutes: 7,
    why: "The 7am and 1pm school wave is a wall of kids, bags, and parents. He watches from the side, never in the flow.",
    bring: BRING_CARRY,
    steps: [
      "Stand at the side of a school gate path, not in the stream.",
      "Treat for each burst of noise.",
      "If the crowd pushes toward you, step into a driveway or onto a bench.",
      "Seven minutes max. This one overstimulates easily. Leave while he is still eating.",
    ],
    goodLooksLike: "Watching, treating, maybe a lean into you that still takes food.",
    ifScared: scaredCopy(),
    whenToStop: stopCopy(7),
    safety: PRECLEAR_SAFETY,
    handbookHref: "/training?open=social",
    logCategory: "New sound",
    logPrompt: "Log this in Socialisation as New sound.",
  },
  {
    id: "noise-build",
    category: "noise",
    title: "Construction, at a distance",
    emoji: "🛠️",
    minutes: 6,
    why: "Drills and piling last for years in Woodlands. Far enough that you can talk over it, close enough that he hears it.",
    bring: BRING_CARRY,
    steps: [
      "Find a worksite you can see from a bus stop or void deck. Stay well back from the fence.",
      "Treat within two seconds of a bang or a reversing beep.",
      "Count five bangs, five treats. Then leave.",
      "If he stops eating on bang one, you are too close. Double the distance tomorrow.",
    ],
    goodLooksLike: "A startle, then a look at you, then a treat. That recovery is the win.",
    ifScared: scaredCopy(),
    whenToStop: stopCopy(6),
    safety: PRECLEAR_SAFETY,
    handbookHref: "/training?open=social",
    logCategory: "New sound",
    logPrompt: "Log this in Socialisation as New sound.",
  },
  {
    id: "car-short",
    category: "car",
    title: "Short ride in the carrier",
    emoji: "🚗",
    minutes: 10,
    why: "The car is how he will see vets, parks, and grandparents. Today is three minutes of engine, not a road trip.",
    bring: BRING_CAR,
    steps: [
      "Put him in the carrier. Belt the carrier on the back seat, not on a lap, not on the floor unbound.",
      "Sit in the driver's seat. Start the engine. Count to 30. Treat through the grid.",
      "Drive around the car park once, slowly. Stop. Treat.",
      "If he is still eating, one loop of the block. Home into the lift in the carrier. Never walk him across the car park on the ground.",
    ],
    goodLooksLike: "Settling on the blanket, taking treats through the grid, no screaming the whole loop.",
    ifScared: scaredCopy(),
    whenToStop: stopCopy(10),
    safety: PRECLEAR_SAFETY,
    handbookHref: "/training?open=social",
    logCategory: "Car / transport",
    logPrompt: "Log this in Socialisation as Car / transport.",
  },
  {
    id: "car-engine",
    category: "car",
    title: "Engine sounds, parked",
    emoji: "🔑",
    minutes: 6,
    why: "The roar at start-up is the bit that scares most puppies. Parked, treats, then off. No moving yet if yesterday's ride was a lot.",
    bring: BRING_CAR,
    steps: [
      "Carrier belted on the back seat. You in the driver's seat.",
      "Treat. Start the engine. Treat within two seconds of the roar.",
      "Idle for two minutes, a slow treat every 20 seconds if he is eating.",
      "Engine off. Treat. Carry him upstairs in the carrier.",
    ],
    goodLooksLike: "Eating through the idle. A freeze that does not eat is the stop line.",
    ifScared: scaredCopy(),
    whenToStop: stopCopy(6),
    safety: PRECLEAR_SAFETY,
    handbookHref: "/training?open=social",
    logCategory: "Car / transport",
    logPrompt: "Log this in Socialisation as Car / transport.",
  },
  {
    id: "car-park",
    category: "car",
    title: "A new car park, still in the carrier",
    emoji: "🅿️",
    minutes: 8,
    why: "Different car parks smell of other dogs' pee on the columns. He stays in the carrier. You do not put him down to sniff.",
    bring: BRING_CAR,
    steps: [
      "Drive to a different block's car park. Keep him in the belted carrier the whole time.",
      "Park. Sit with the windows cracked. Treat through the grid for two minutes of new smells.",
      "Do not open the carrier in the car park. Do not let him sniff the columns.",
      "Drive home. Carrier upstairs.",
    ],
    goodLooksLike: "Nose working through the grid, still taking treats.",
    ifScared: scaredCopy(),
    whenToStop: stopCopy(8),
    safety: PRECLEAR_SAFETY,
    handbookHref: "/training?open=social",
    logCategory: "Car / transport",
    logPrompt: "Log this in Socialisation as Car / transport.",
  },
  {
    id: "car-drive",
    category: "car",
    title: "Drive-through, stay in the box",
    emoji: "🥤",
    minutes: 10,
    why: "A drive-through is voices in a window, a bag of food, and a slow roll. He watches from the carrier. He does not get the fries.",
    bring: BRING_CAR,
    steps: [
      "Carrier belted in the back. Order something small for you.",
      "Treat him when the speaker crackles.",
      "Treat him when the window opens.",
      "Do not pass food to him from the bag. His treats are the pea-sized ones you brought.",
      "Home. Carrier upstairs. You drink the drink.",
    ],
    goodLooksLike: "Watching the window, taking his own treats, not screaming at the speaker.",
    ifScared: scaredCopy(),
    whenToStop: stopCopy(10),
    safety: PRECLEAR_SAFETY,
    handbookHref: "/training?open=social",
    logCategory: "Car / transport",
    logPrompt: "Log this in Socialisation as Car / transport.",
  },
  {
    id: "handling-mouth",
    category: "handling",
    title: "Mouth touches, paid in treats",
    emoji: "🦷",
    minutes: 5,
    why: "Chesa's teeth-brushing nights only work if lips already predict chicken. Today is a lip lift, not a toothbrush.",
    bring: BRING_INDOOR,
    steps: [
      "Sit with him on your lap. Treat for sitting.",
      "Touch the side of his muzzle. Treat within two seconds.",
      "Lift the lip for one second so you see a tooth. Treat.",
      "If he stays loose, do the other side once.",
      "Stop. Do not pick up the toothbrush today unless he was butter.",
    ],
    goodLooksLike: "Taking treats, maybe a lick. A snap or freeze is the stop line.",
    ifScared: scaredCopy(),
    whenToStop: stopCopy(5),
    safety: PRECLEAR_SAFETY,
    handbookHref: "/training?open=handling",
    logCategory: "Handling / body touch",
    logPrompt: "Log this in Socialisation as Handling / body touch.",
  },
];

const GROUND_SAFETY: string[] = [
  "This is a ground mission. It still needs the SingVet nod after the Friday 16 Oct core. If the vet has not said yes, do the carry version instead.",
  "No greeting strange dogs. You do not know their vaccination status.",
  "No sniffing pee spots or other dogs' droppings. Disease still spreads this way.",
  "Let him choose whether to approach people. A grabbed-at puppy learns strangers are scary.",
  "Pair every new thing with a pea-sized treat from your hand to his mouth within two seconds.",
  "End while he is still comfortable. Stop when he stops taking treats.",
];

const GROUND_MISSIONS: SocialMission[] = [
  {
    id: "ground-sniffari",
    category: "ground",
    title: "Sniffari on the 7:15am patch",
    emoji: "👃",
    minutes: 10,
    why: "A sniffari is a walk where his nose leads and you follow. Ten minutes of sniffing tires him more than a march. Only after SingVet says the grass is allowed.",
    bring: [TREAT_POUCH, "Harness and lead, snug but not tight", POOP_BAG, WATER],
    steps: [
      "Harness on at home. Treat for putting his head through.",
      "Carry him in the lift. Put him down only on the patch SingVet cleared, not in the lobby.",
      "Let the lead go slack. He sniffs. You wait. Count ten sniffs, ten quiet 'yes' and treats.",
      "Do not march. Do not pull him off a smell unless it is droppings. Then a cheerful 'this way' and a treat on the move.",
      "Five to ten minutes. Carry him back into the lift.",
    ],
    goodLooksLike: "Nose down, tail easy, still taking treats. Not lunging, not shutting down.",
    ifScared: scaredCopy(),
    whenToStop: stopCopy(10),
    safety: GROUND_SAFETY,
    handbookHref: "/training?open=social",
    logCategory: "New place",
    logPrompt: "Log this in Socialisation as New place.",
  },
  {
    id: "ground-park-edge",
    category: "ground",
    title: "Park-edge watching",
    emoji: "🌳",
    minutes: 10,
    why: "The park next door is a lot. The edge is the lesson. He sees dogs and people. He does not have to join them.",
    bring: [TREAT_POUCH, "Harness and lead", POOP_BAG],
    steps: [
      "Only if SingVet has nodded. Sit on a bench at the park edge, lead short, him on the ground beside you or on your lap if the grass is crowded.",
      "Treat for looking at a dog in the distance.",
      "If a dog runs over, stand, turn away, and make space. You do not owe anyone a greeting.",
      "Ten minutes. Home before he is tired-gremlin.",
    ],
    goodLooksLike: "Watching, treating, maybe a wag at a distant dog. A tight tail or freeze means more distance tomorrow.",
    ifScared: scaredCopy(),
    whenToStop: stopCopy(10),
    safety: GROUND_SAFETY,
    handbookHref: "/training?open=social",
    logCategory: "New dog / animal",
    logPrompt: "Log this in Socialisation as New dog / animal.",
  },
  {
    id: "ground-calm-dog",
    category: "ground",
    title: "One calm, vaccinated dog",
    emoji: "🐕",
    minutes: 8,
    why: "One known, gentle, fully vaccinated adult dog beats a dog-run ambush. Parallel walking, not face-to-face crashing.",
    bring: [TREAT_POUCH, "Harness and lead", "The other owner's agreement in advance"],
    steps: [
      "Confirm the other dog is vaccinated and calm. Meet on a quiet path, not at a gate.",
      "Walk the same direction, two metres apart. Treat Paddington for looking at the other dog and then back at you.",
      "If both are loose, let them sniff for three seconds, then call him away and treat.",
      "Stop before anyone gets rude. One short hello is a win.",
    ],
    goodLooksLike: "Curved body, loose tail, able to take a treat after the sniff. Stiff, still, or staring is a break.",
    ifScared: scaredCopy(),
    whenToStop: stopCopy(8),
    safety: GROUND_SAFETY,
    handbookHref: "/training?open=social",
    logCategory: "New dog / animal",
    logPrompt: "Log this in Socialisation as New dog / animal.",
  },
  {
    id: "ground-715",
    category: "ground",
    title: "The 7:15am toilet route",
    emoji: "☀️",
    minutes: 10,
    why: "This is the weekday rhythm once grass is allowed: crate to lift to the same patch, wee, praise, home, breakfast.",
    bring: [TREAT_POUCH, "Harness and lead", POOP_BAG],
    steps: [
      "Straight from crate to lift. Carry him in the lobby. Put him down on the patch, not on the tiles.",
      "Quiet cue 'go potty' while he wees. Pea-sized treat within two seconds of finishing, at the spot.",
      "A short sniff (two minutes), then home. Breakfast after.",
      "Skip this in the 10am to 5pm heat. Pavement burns paws.",
    ],
    goodLooksLike: "Wee on the patch, treat, maybe a poo. Accidents in the lift mean you were too slow from the crate.",
    ifScared: scaredCopy(),
    whenToStop: stopCopy(10),
    safety: GROUND_SAFETY,
    handbookHref: "/handbook/first-day",
    logCategory: "New place",
    logPrompt: "Log the wee in Toilet, and this outing in Socialisation as New place.",
  },
  {
    id: "ground-surface",
    category: "ground",
    title: "New ground under his paws",
    emoji: "🛤️",
    minutes: 8,
    why: "Grass, tiles, rubber playground mats, and metal drains all feel different. One new surface a day, after the nod.",
    bring: [TREAT_POUCH, "Harness and lead"],
    steps: [
      "Pick one surface: the rubber mat at the playground edge, a metal drain cover, or a strip of grass SingVet allowed.",
      "Put him down on it. Treat within two seconds.",
      "Three steps on it. Treat. Three steps off. Treat.",
      "If he refuses, you carry him onto it for one second, treat, and pick him up. Try again tomorrow.",
    ],
    goodLooksLike: "Walking onto it without being dragged. Taking treats on the new surface.",
    ifScared: scaredCopy(),
    whenToStop: stopCopy(8),
    safety: GROUND_SAFETY,
    handbookHref: "/training?open=social",
    logCategory: "New surface",
    logPrompt: "Log this in Socialisation as New surface.",
  },
];

export const PRECLEAR_MISSIONS: SocialMission[] = [...INDOOR_MISSIONS, ...CARRY_MISSIONS];
export const ALL_GROUND_MISSIONS: SocialMission[] = GROUND_MISSIONS;

function daysHomeOn(date: Date): number {
  const a = new Date(date.getFullYear(), date.getMonth(), date.getDate()).getTime();
  const b = new Date(HOMECOMING_ISO + "T00:00:00").getTime();
  return Math.round((a - b) / 86400000);
}

function pickMission(pool: SocialMission[], date: Date): SocialMission {
  return pool[Math.abs(dayIndex(date)) % pool.length];
}

/** Today's mission, or null before 23 Sep. */
export function socialMissionFor(date: Date): SocialMission | null {
  if (!hasLanded(date)) return null;
  if (groundWalksAllowed(date)) return pickMission(GROUND_MISSIONS, date);
  const home = daysHomeOn(date);
  if (home <= 2) return pickMission(INDOOR_MISSIONS, date);
  return pickMission(CARRY_MISSIONS, date);
}

export function missionCategoriesIn(pool: SocialMission[]): SocialCategory[] {
  return [...new Set(pool.map((m) => m.category))];
}

/** Used by tests: the 16-week core ISO so they do not hard-code a second copy. */
export const MISSION_CORE_ISO = CORE_16W_ISO;
